version: "3"

services:
    flask:
        build: ./server/flask
        container_name: flask
        restart: always
        environment:
            - APP_NAME=FlaskServer
        expose:
            - 8081
        depends_on:
            - redis
    nginx:
        build: ./nginx
        container_name: nginx
        restart: always
        ports:
            - "5000:5000"
    redis:
        image: redis:alpine
        command: redis-server --port 6379
        container_name: redis_boot
        restart: always
        hostname: redis_boot
        labels:
            - "name=redis"
            - "mode=standalone"
        ports:
            - 6379:6379